# Generated by Django 2.1.7 on 2019-03-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dweet',
            old_name='crBy',
            new_name='dweeterId',
        ),
        migrations.RemoveField(
            model_name='dweet',
            name='crDate',
        ),
        migrations.RemoveField(
            model_name='dweet',
            name='dwweterId',
        ),
        migrations.RemoveField(
            model_name='dweet',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='dweet',
            name='likeCount',
        ),
        migrations.RemoveField(
            model_name='dweet',
            name='lmodBy',
        ),
        migrations.RemoveField(
            model_name='dweet',
            name='lmodDate',
        ),
        migrations.RemoveField(
            model_name='dweet',
            name='text',
        ),
    ]
