# Generated by Django 2.1.7 on 2019-03-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190324_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dweet',
        ),
    ]
