# Generated by Django 2.1.7 on 2019-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_dweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dweeterId', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=256)),
                ('likeCount', models.IntegerField(default=0)),
                ('crDate', models.DateTimeField(auto_now_add=True)),
                ('crBy', models.IntegerField(default=0)),
                ('lmodDate', models.DateTimeField(auto_now=True)),
                ('lmodBy', models.IntegerField()),
                ('isActive', models.IntegerField(default=1)),
            ],
        ),
    ]
