# Generated by Django 2.1.7 on 2019-03-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='lmodBy',
            field=models.IntegerField(default=0),
        ),
    ]
