# Generated by Django 2.1.7 on 2019-03-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dweetId', models.IntegerField(default=0)),
                ('dweeterId', models.IntegerField(default=0)),
                ('likedBy', models.IntegerField(default=0)),
                ('crDate', models.DateTimeField(auto_now_add=True)),
                ('crBy', models.IntegerField(default=0)),
                ('lmodDate', models.DateTimeField(auto_now=True)),
                ('lmodBy', models.IntegerField(default=0)),
                ('isActive', models.IntegerField(default=1)),
            ],
        ),
    ]
